name: Update repo in Databricks
# This action runs with each merge to <branch-name>
on:
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repo in Databricks
        env:
          # Databricks Access Token stored in Github Actions Secrets
          DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
        run: |
          echo "Calling repos Update API to update branch."
          curl -n -X PATCH https://adb-1358927967868039.19.azuredatabricks.net/api/2.0/repos/49597510054044 \
            -H 'Authorization: Bearer '$DATABRICKS_ACCESS_TOKEN \
            -d '{"branch": "dev"}'
